language: node_js
cache: yarn
install: yarn
jobs:
  include:
    - stage: Unit tests
      node_js:
        - 8
      install: yarn
      script: npm test
    - stage: Release
      node_js: 8
      script: tools/npm-publish.sh
      after_script: tools/gh-release.sh
