language: node_js
cache: yarn
install: yarn
jobs:
  include:
    - stage: Unit tests
      node_js:
        - 8
      install: yarn
      script: npm test
    - stage: Release
      if: branch = master
      node_js: 8
      script: echo "Release"
