language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - 8
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
install: yarn
script: npm test
after_success:
  - npm run semantic-release
