language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - 8
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: Unit tests
      install: yarn
      script: npm test
    - stage: Release
      script: echo "Releasing to npm, or not... 📦"
      after_success:
        - npm run semantic-release
